IMAGE_NAME = "ubuntu/focal64"
BASE_IP = "192.168.50"
N_MASTERS = 1
N_WORKERS = 2

Vagrant.configure("2") do |config|

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end

    # Required configuration for kubeadm
    # See: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
    config.vm.provision "shell", path: "./provision-all.sh", privileged: false
      
    (1..N_MASTERS).each do |i|
        config.vm.define "k8s-control-#{i}" do |control|
            NODE_IP = "#{BASE_IP}.#{i + 9}"
            control.vm.box = IMAGE_NAME
            control.vm.network "private_network", ip: NODE_IP
            control.vm.hostname = "k8s-control-#{i}"
            control.vm.provision "shell", path: "./provision-control-node.sh", args: NODE_IP, privileged: false
        end
    end

    (1..N_WORKERS).each do |i|
        config.vm.define "k8s-node-#{i}" do |node|
            NODE_IP = "#{BASE_IP}.#{i + 9 + N_MASTERS}"
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: NODE_IP
            node.vm.hostname = "k8s-node-#{i}"
            node.vm.provision "shell", path: "./provision-worker-node.sh", privileged: false
        end
    end
end
